version: '3.8'
services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: ai_lie_detector_server
    volumes:
      - ./server:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped