services:
  - type: web_service
    name: ai_lie_detector-backend
    env: docker
    repo: https://github.com/damiangohrh123/ai_lie_detector
    branch: main
    root: server
    dockerfilePath: server/Dockerfile
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    instances:
      type: pro
      count: 1
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"